# 技術ノート

[[note]]
date = 0000-00-00
from = ""
contents = ""

[[note]]
date = 2026-08-01
from = "[ChatGPT](https://chatgpt.com/g/g-p-6a6a9c42099c819191f6af4fa647b628/c/6a6cd85d-e278-83ee-b343-3c82e91199fd)"
contents = "文に予測に反する変化をつけることで面白みになる。また、変化の予測にも反するといい。比喩、修飾、文長、語順、語彙、リズム、漢字率など。"

[[note]]
date = 2026-07-12
from = ""
contents = "比喩表現を色や香りから五感や第六感に延長する。喜びの竪琴がかき鳴らされる。情熱の味わいがしている。ひなびた風が第六の感覚に触れた。"

[[note]]
date = 2026-07-09
from = "rea-001/num-1"
contents = "主語から始めると文として強いイメージになる。形容詞や形容動詞、副詞などで始めることで柔らかいイメージを作る。"
