# 技術ノート

[[note]]
date = !
from = ""
technique = ""

[[note]]
date = 2026-07-12
from = ""
technique = "比喩表現を色や香りから五感や第六感に延長する。喜びの竪琴がかき鳴らされる。情熱の味わいがしている。ひなびた風が第六の感覚に触れた。"

[[note]]
date = 2026-07-09
from = "rea-001/num-1"
technique = "主語から始めると文として強いイメージになる。形容詞や形容動詞、副詞などで始めることで柔らかいイメージを作る。"
