[data]
title = "これさえ知っておけば、小説は簡単に書けます。"
ISBN = "9784396116903"

[[memo]]
num = 1
date = 2026-07-12
page_start = 143
page_end = 143
target = [
  """\
  （小説の一行目について）断言しているにもかかわらず謎のある文章""",
  """\
  （小説の一行目について）何かを言い切って、なおかつ謎があると良いです。"""
]
opinion = """\
"""