[data]
title = "日本語の文体"
ISBN = "9784000042178"

[[memo]]
num = 1
date = 2026-07-12
page_start = 24
page_end = 24
target = """\
第一は、男性は冷静に観察して捉えた客観的な事実をもとに、感情を交えずに記述する傾向があるという点だ。――中略――第二は、女性の作中人物に対して、男性より女性の方が内側から描く傾向が強いという点だ。"""
opinion = """\
僕が女性を描くときに参考になるかもしれない。"""